language: python
dist: xenial
sudo: required

python:
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - "make setup"
    - "pip install -U ."
script:
    - python3 -m coverage run -m bowler.tests
    - python3 -m coverage report
after_success:
    - "coveralls"

matrix:
  include:
    - name: black
      python: "3.7"
      install:
        - pip install black
      script:
        - black --check bowler setup.py

    - name: mypy
      python: "3.7"
      install:
        - pip install mypy
      script:
        - mypy -m bowler
